### ISSUE TITLE
셋업

### ISSUE THREAD

**Issue by bamjun** [OZ-Coding-School/oz_03_collabo-001-BE#1]
포이트리설정
```bash
poetry new babydog
```

```bash
poetry add django
```

정하기
파이썬 버전.
장고 버전.

**Comment by cmmnnie** [comment]
파이썬, 장고 무슨 버전을 쓸지에 따라 결정을 해야 할 것 같아요

**Comment by cmmnnie** [comment]
3.12파이썬,  장고 4.2 이상

**Comment by bamjun** [comment]
allauth 쓰실건가요 ?!

**Comment by youngkwangjoo** [comment]
넹 공식문서보니까 allauth를 3.12까지 지원해주네요 장고는 4.2+까지 지원해주는거보니 최신버젼도 괜찮을꺼같은데 범준님은 어때요

**Comment by bamjun** [comment]
좋아욥 .
