### ISSUE TITLE
로그인 오류 해결 

### ISSUE THREAD

**Issue by youngkwangjoo** [OZ-Coding-School/oz_03_collabo-001-BE#120]
**버그 설명**
1. 오류 엔진엑스 컨테이너 이름 불일치
컨테이너 이름 불일치로 서버 500을 계속 반환해서 이 부분을 수정함

2. httpresponseredirect 를 사용한 쿠키전송
멘토링 시간 때 바꾼 이 부분에서 오류가 발생했습니다.
자세히 설명하면
HttpResponseRedirect 함수는 사이드 리다이렉션을 주로 할 때 사용되고, 브라우저는 리다이렉트를 받으면 즉시 새 URL로 이동합니다. 이때 설정한 커스텀 헤더는 대부분 무시됩니다. 리다이렉트된 요청은 새로운 요청으로 간주되어, 원래 설정한 CORS 헤더가 적용되지 않는다고 합니다.  그래서 HRR은 페이지 이동에 적합한 함수고, 헤더오류가 발생하는 우리 프로젝트에는 적절하지 않은듯 합니다. 
 이 해결책으로 원래 코드 jsonresponse를 사용했는데, 이 함수는 응답 헤더를 쉽게 수정할 수 있어, Access-Control-Allow-Credentials, Access-Control-Allow-origin를 포함한 필요한 CORS 헤더를 추가해서 오류를 고칠 수 있었습니다. 
HttpResponseRedirect를 사용할때 헤더를 추가하려고 엔진엑스에 add header를 시도했지만 엔진엑스에 추가하면 헤더가 2개가 나오고, 장고나 엔진엑스 중 한개의 헤더를 지우면 아예 응답헤더가 없어서 로그인이 실패하는 현상이 발생했습니다. 
  jsonresponse 이 함수 자체가 문제인점은 없으나, 단점으로는 커스텀이다보니 추가적인 헤더 설정이 필요할 수 있고, 프론트엔드에서 리디렉션 로직을 구현해야한다는 점인데, 우리 로그인 시스템은 로컬에서 이미 로직을 짜놓은 상태라 문제 없어보입니다.

그래서 어제 조언에도 불구하고, 다시 jsonresponse 원래 함수로 merge해놓은 상태이고, 로그인 성공을 한 상태입니다.

**Comment by bamjun** [comment]
<img width="971" alt="image" src="https://github.com/user-attachments/assets/14c1430e-5f85-43ba-ad66-e4ca22cbfae3">

<img width="701" alt="image" src="https://github.com/user-attachments/assets/9c773518-7ca1-4a30-831c-33b172c4f6ad">

서브도메인 api 없애고 .dogandbaby.co.kr 로 돼야할꺼같아요.

쿠키에 있는거 프론트에서 쓰려면, 같은 도메인에서 가능하지만, 서브 도메인이 있으면 프론트에서 못가져오는거 같아요


https://yelee.tistory.com/85

**Comment by bamjun** [comment]
[#](https://yelee.tistory.com/85)

**Comment by youngkwangjoo** [comment]
해결 완료
