### ISSUE TITLE
Fix: 미디어 파일 s3 설정

### ISSUE THREAD

**Issue by bamjun** [OZ-Coding-School/oz_03_collabo-001-BE#145]
프로덕트 환경에서 미디어파일을 s3에 저장해서, 로드벨런스 사용시, 전체 서버에서 동일한 미디어 파일 조회가능하게 하기...

              이거 빼면 s3 작동안해요... ㅠ

_Originally posted by @bamjun in https://github.com/OZ-Coding-School/oz_03_collabo-001-BE/pull/133#discussion_r1734132120_

**Comment by bamjun** [comment]
@youngkwangjoo s3 설정 그냥 이유가 있어서, 뺀건가요 ?

**Comment by youngkwangjoo** [comment]
어...? 실수로뺀거같은데요...?

**Comment by bamjun** [comment]
다시 넣을께요
