### ISSUE TITLE
social login : naver

### ISSUE THREAD

**Issue by youngkwangjoo** [OZ-Coding-School/oz_03_collabo-001-BE#20]
**기능 설명**
네이버 소셜로그인

**추가 정보**

**Comment by bamjun** [comment]
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/a73671b3-009e-43c5-a1b0-ca0afff87663">

Priority 중요도, p0 최고 중요한 기능, p2 덜중요한 기능

size 작업량.. xs 작업량이 엄청 작다, xl 작업량이 엄청 많다.

estimate 예상 작업시간, 프로젝트에 작업시간 총합이 보여짐
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/71b9ccda-2344-439e-8950-98d23d53d2ad">

start date 작업 시작 일
end date 작업 완료 일


iteration은 아래 글 참고해보세욥. 저두 잘몰라서 ㅠ_ㅠ
https://velog.io/@simej1214/Github-Iteration%EA%B3%BC-Milestone%EC%9D%98-%EC%B0%A8%EC%9D%B4

**Comment by bamjun** [comment]
![image](https://github.com/user-attachments/assets/7c09fcee-500d-49e9-9a31-0c1e05803323)

요기는 작업하고 있는 브랜치 선택가능합니당
