### ISSUE TITLE
ec2 컨테이너 문제

### ISSUE THREAD

**Issue by youngkwangjoo** [OZ-Coding-School/oz_03_collabo-001-BE#88]
**버그 설명**
1. ec2 web이랑 rds가 연결이 안되는중
2. 엔진엑스를 컨테이너 안에서 돌리고, aws 로드밸런서를 쓰는 방안 or 컨테이너 안에서 ssl 인증서를 받는 방법을 멘토님이 추천하심 

**재현 방법**
버그를 재현하기 위한 단계:
1. 터미널에 들어가서 받은 pem키로 접속을 합니다
2. 도커 컨테이너를 실행하면 rds 마이그레이션 오류가 발생.
3. 엔진엑스 컨테이너가 돌아가지 않음

**예상한 동작**
Rds 환경설정은 다 되어있는거같은데 뭐가 문제인지 모르겠음 

**스크린샷**
![스크린샷 2024-08-23 오전 1 43 57](https://github.com/user-attachments/assets/1ee07ee1-1060-440d-9926-30de855a443b)

**추가 정보**
문제에 대한 추가 정보를 여기에 작성해 주세요.

**Comment by youngkwangjoo** [comment]
금요일에 열심히 슈팅해보겠습니다

**Comment by bamjun** [comment]
1차적으로 맨처음에 독커 실행했을때 .env 파일이 없이 이미지 파일이 생성됐는데, 이거를 삭제안하고, 하다보니, 새로운 .env 파일이 적용이 안돼서, rds에 접속이 안돼더라구요...


2차적으로 rds에 db가 생성이 안돼서, 접속이 안돼고 있습니다. ㅠㅠㅠ
아래 사진처럼 `DB 이름`이 `-` 표시 돼어있으면 db가 없는 거라는거군요.. ㅠ

<img width="166" alt="image" src="https://github.com/user-attachments/assets/35792d63-596f-4aee-850a-5fbcb368fcec">


[aws 설명링크](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToPostgreSQLInstance.html)

![image](https://github.com/user-attachments/assets/d6b7263f-8e39-4403-8287-1d0ae5add8b2)

**Comment by youngkwangjoo** [comment]
해결 완료
